### ISSUE TITLE
why on earth did you just dump a tarball of openwrt in here?

### ISSUE THREAD

**Issue by dtaht** [wrt1900ac/opensource#2]
I mean, you could merely have pulled from the openwrt git repo and layered your changes on top. Not having to be a code archaeologist to figure out what bugs you have inherited would be nice. 

You have a version of openssl susceptible to heartbleed in here, for example.

**Comment by lra** [comment]
I agree.

Do you guys know to use git at all?
Also github discourages putting binaries in the repo: https://github.com/blog/1302-goodbye-uploads

You should only put the patches against OpenWRT here and explain anyone how to patch it. And provide an easy download link ready to be used elsewhere.

**Comment by saberone** [comment]
Before I bought the Linksys I did some reading of reviews, and the all seemed positive. The openwrt compatibility/support was a very important point to me since I was previously running it on mij Netgear WNDR3700. But after two days I'm a bit disappointed, the openwrt support is rather

On topic. This repo is really an insult to the buyers of the WRT1900ac AND github AND opensource. And  why is it called "opensource" and it's filled with binaries? SIGH.

**Comment by dtaht** [comment]
I whined. I have no idea what is happening here. But closing the bug.

**Comment by lra** [comment]
Well this is a legit ticket, u should let this open to let other people (like me) know that you should not buy this router if you are looking for a OpenWRT router.

**Comment by JamesLaugesen** [comment]
@lra the McWRT project (https://github.com/Chadster766/McWRT) is going quite well (Attitude Adjustment is stable.). Everyone should head there.

This repo has always been dead and just a disappointing demonstration of how Belkin (still) don't understand open-source or OpenWRT communities. Although they deserve a bit of credit for trying, and engaging (very slowly.) with the OpenWRT team.
